# Generated by Django 4.1.6 on 2023-02-07 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'address', 'verbose_name_plural': 'addresses'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'customer', 'verbose_name_plural': 'customers'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'subscription', 'verbose_name_plural': 'subscriptions'},
        ),
        migrations.AddField(
            model_name='gym',
            name='opened_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='due_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 7, 15, 59, 18, 447362, tzinfo=datetime.timezone.utc), null=True, verbose_name='Expires'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscription_number',
            field=models.CharField(default=0, max_length=8),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='visits_count',
            field=models.IntegerField(),
        ),
    ]
